import './globals.css'
import { AuthModal } from '../components/auth-modal'
import { TTSProvider } from '../contexts/tts-context'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TTSProvider>
          <AuthModal />
          {children}
        </TTSProvider>
      </body>
    </html>
  )
}
